export const START_FETCHING_ACCESSORIES = "START_FETCHING_ACCESSORIES";
export const FETCHING_ACCESSORIES_SUCCESS = "FETCHING_ACCESSORIES_SUCCESS";
export const FETCHING_ACCESSORIES_FAIL = "FETCHING_ACCESSORIES_FAIL";


